version: '2'

services:

    ganache:
        container_name: ganache
        build: ./Ganache/
        expose:
            - "7454"
        ports: 
            - "7454:7454"
        environment:
            - NETWORKID=6
            - PORT=7454
        restart: always

    truffle:
        container_name: truffle
        build: ./Truffle/
        volumes:
            - ./docker_data/ethereum/:/data/
        working_dir: /data
        links:
            - ganache:ganache
        restart: always

    geth:
        container_name: geth
        build: ./Geth/
        restart: always
        links:
            - ganache:ganache
