version: '2'
services:
	postgresql:
		images: sameersbn/postgresql:9.4
		restart: always
		volumes:
			- /etc/localtime:/etc/localtime:ro
			- /data/docker_data/postgresql/data:/var/lib/postgresql
		environment:
			- DB_NAME=gitlabhq_production
			- DB_USER=gitlab
			- DB_PASS=password
	redis:
		images: sameersbn/redis
		restart: always
		volumes:
			- /etc/localtime:/etc/localtime:ro
	gitlab:
		images: sameersbn/gitlab:7.11.2
		restart: always
		volumes:
			- /etc/localtime:/etc/localtime:ro
			- /data/docker_data/gitlab/data:/home/git/data
		ports:
			- "2200:22"
			- "8080:80"
		environment:
			- GITLAB_SSH_PORT=2200
			- GITLAB_BACKUPS=daily
			- GITLAB_HOST=
			- GITLAB_SIGNUP=true
			- GITLAB_GRAVATAR_ENABLED=false
			- SMTP_DOMAIN=
			- SMTP_HOST=
			- SMTP_PORT=
			- SMTP_USER=
			- SMTP_PASS=
		links:
			- postgresql:postgresql
