version: '2'
services:
    mysql:
        image: daocloud.io/library/mysql
        expose: 
            - "3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ~/data/docker_data/mysql_3306:/data
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    php-fpm:
        build: ./PHP7.1/
        expose:
            - "9000"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ~/data/docker_data/php-fpm_9000:/data
        restart: always
    nginx:
        build: ./OpenResty/
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        volumes_from:
            - php-fpm
        links:
            - mysql:mysql
            - php-fpm:php-fpm
