version: '2'

services:

    ganache:
    	build: ./Ganache/
        expose:
            - "7454"
        ports: 
            - "7454:7454"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
	    - PORT=7454
            - NETWORKID=6
        restart: always

    truffle:
        build: ./Truffle/
        volumes:
	    - ~/data/eth/:/data/
            - /etc/localtime:/etc/localtime:ro
        links:
            - ganache:ganache
        restart: always

    geth:
        build: ./Geth/
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
        links:
            - ganache:ganache
